import { GoBackButton } from '@/components/GoBack/GoBack';
import { GoBack } from '@/components/icons/GoBack';
import { PlansListPage } from '@/features/plans/plans-list.page';
import Head from 'next/head'
import Link from 'next/link';
export default function Workout() {
  return (
    <>
      <Head>
        <title>Shark Shape</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ marginTop: 64 }}>
        <GoBackButton />
        <PlansListPage />
      </main>
    </>
  )
}
