import { GoBackButton } from '@/components/GoBack/GoBack';
import { GoBack } from '@/components/icons/GoBack';
import { HomePage } from '@/features/home/home.page'
import { WorkoutListPage } from '@/features/workout/workout-list.page';
import Head from 'next/head'
import Link from 'next/link';
import {useRouter} from 'next/router';

export default function Workout() {
  const router = useRouter()
  const { id } = router.query

  return (
    <>
      <Head>
        <title>Shark Shape</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ marginTop: 64 }}>
        <GoBackButton />
        <WorkoutListPage />
      </main>
    </>
  )
}
